---
- name: Install rabbitmq package on {{ ansible_distribution }}
  become: yes
  package:
    name: rabbitmq-server
    state: present
  notify:
    - restart rabbitmq
  tags: rabbitmq

- name: Ensure rabbitmq is enabled and running
  become: yes
  service:
    name: rabbitmq-server
    enabled: yes
    state: started
  tags: rabbitmq

- name: Add RabbitMQ plugins
  become: yes
  rabbitmq_plugin:
    names: "{{ rabbitmq_plugins }}"
    state: enabled
    new_only: yes
    # the EL6 RPM for rabbitmq-server does not place the rabbitmq-plugins binary in the search path (other distro's packages do, including EL7). Prefix adds it to the binary search path.
    prefix: "{{ rabbitmq_use_el6_prefix | ternary(rabbitmq_el6_prefix, omit) }}"
  when: rabbitmq_plugins != ''
  tags: rabbitmq
